#!/usr/bin/env node
/**
 * Token build script — generates CSS variables and TS constants from tokens/source.json
 * This is the single source of truth pipeline (style-dictionary pattern).
 *
 * Usage: node tokens/build.cjs
 * Output: src/styles/generated-tokens.css + src/lib/generated-tokens.ts
 */
const fs = require('fs');
const path = require('path');

const source = JSON.parse(fs.readFileSync(path.join(__dirname, 'source.json'), 'utf8'));
const root = path.join(__dirname, '..');

// ========================================
// CSS GENERATOR
// ========================================
function generateCSS() {
  let css = '/* AUTO-GENERATED by tokens/build.cjs — do not edit directly.\n';
  css += ' * Source: tokens/source.json — Magenta/Cyan token system for Discomplement.\n';
  css += ' * Regenerate after editing source.json: node tokens/build.cjs\n';
  css += ' */\n\n';

  css += '/* ========================================\n   TIER 1: PRIMITIVES (raw, theme-agnostic)\n   ======================================== */\n\n';
  css += ':root {\n';

  for (const [family, ramp] of Object.entries(source.color)) {
    if (family === 'anchor') continue;
    if (typeof ramp === 'string') continue;
    css += `  /* ${family} */\n`;
    for (const [shade, value] of Object.entries(ramp)) {
      css += `  --${family}-${shade}: ${value};\n`;
    }
    css += '\n';
  }

  css += '  /* Brand anchors — logo & dark-surface accent only */\n';
  css += `  --anchor-semantic: ${source.color.anchor.semantic};\n`;
  css += `  --anchor-code: ${source.color.anchor.code};\n`;

  css += '\n  /* Neutrals */\n';
  for (const [shade, value] of Object.entries(source.color.neutral)) {
    css += `  --neutral-${shade}: ${value};\n`;
  }

  css += '\n  /* Status */\n';
  for (const [name, value] of Object.entries(source.color.status)) {
    css += `  --${name}: ${value};\n`;
  }

  css += '\n  /* Typography */\n';
  css += `  --font-display: ${source.font.display};\n`;
  css += `  --font-body: ${source.font.body};\n`;
  css += `  --font-mono: ${source.font.mono};\n`;
  css += '\n  /* Fluid type scale */\n';
  for (const [name, value] of Object.entries(source.fontSize)) {
    css += `  --text-${name}: ${value};\n`;
  }

  css += '\n  /* Radius */\n';
  for (const [name, value] of Object.entries(source.radius)) {
    css += `  --radius-${name}: ${value};\n`;
  }

  css += '\n  /* Spacing */\n';
  for (const [name, value] of Object.entries(source.spacing)) {
    css += `  --space-${name}: ${value};\n`;
  }

  css += '\n  /* Motion */\n';
  css += `  --ease-standard: ${source.motion.easeStandard};\n`;
  css += `  --ease-emphasized: ${source.motion.easeEmphasized};\n`;
  css += `  --duration-fast: ${source.motion.durationFast};\n`;
  css += `  --duration-normal: ${source.motion.durationNormal};\n`;
  css += `  --duration-slow: ${source.motion.durationSlow};\n`;

  css += '\n  /* Glow shadows */\n';
  css += '  --glow-semantic: 0 0 24px rgba(200, 50, 140, 0.15);\n';
  css += '  --glow-code: 0 0 24px rgba(40, 160, 210, 0.15);\n';
  css += '  --glow-bridge: 0 0 24px rgba(106, 92, 192, 0.12);\n';

  css += '}\n\n';

  return css;
}

// ========================================
// TIER 2 GENERATOR — one block per theme in source.themes
// ========================================

/** Theme ids in emission order: the default first, then the rest as authored.
 *  Order is load-bearing. `:root` and `[data-theme='x']` have equal specificity,
 *  so a later block wins on source order alone — the default has to come first
 *  or it would override every explicitly-selected theme. */
function themeIdsInEmissionOrder(themes) {
  const ids = Object.keys(themes);
  const defaults = ids.filter((id) => themes[id].$default);
  if (defaults.length !== 1) {
    throw new Error(
      `themes: expected exactly one theme with "$default": true, found ${defaults.length} (${defaults.join(', ') || 'none'})`
    );
  }
  return [defaults[0], ...ids.filter((id) => id !== defaults[0])];
}

/** Every theme must define the same alias set. A theme missing an alias does not
 *  fail loudly at runtime — it silently inherits whatever block ran last, or
 *  resolves to nothing. Cheaper to catch here. */
function assertThemeParity(themes, order) {
  const reference = Object.keys(themes[order[0]].tokens).sort();
  for (const id of order.slice(1)) {
    const actual = Object.keys(themes[id].tokens).sort();
    const missing = reference.filter((k) => !actual.includes(k));
    const extra = actual.filter((k) => !reference.includes(k));
    if (missing.length || extra.length) {
      throw new Error(
        `theme "${id}" does not match "${order[0]}": ` +
          `${missing.length ? `missing [${missing.join(', ')}]` : ''}` +
          `${missing.length && extra.length ? '; ' : ''}` +
          `${extra.length ? `unexpected [${extra.join(', ')}]` : ''}`
      );
    }
  }
}

/** Flat map of every Tier 1 primitive, parsed back out of the generated CSS so
 *  the naming logic lives in exactly one place (generateCSS) rather than twice. */
function primitiveMap(tier1Css) {
  const map = {};
  for (const [, name, value] of tier1Css.matchAll(/--([a-z0-9-]+):\s*([^;]+);/g)) {
    map[name] = value.trim();
  }
  return map;
}

/** Resolve a token value to a literal colour by following `var(--x)` references
 *  through the theme's own aliases and then the primitives. Used to give the
 *  theme picker a swatch that shows each theme's real colours rather than the
 *  currently-applied ones — a `var()` in the DOM would resolve against whichever
 *  theme is active, which is exactly the wrong thing for a preview. */
function resolveValue(value, themeTokens, primitives) {
  let current = value.trim();
  for (let depth = 0; depth < 10; depth += 1) {
    const match = /^var\(--([a-z0-9-]+)\)$/.exec(current);
    if (!match) return current;
    const key = match[1];
    const next = themeTokens[key] ?? primitives[key];
    if (next === undefined) {
      throw new Error(`token "--${key}" is referenced but never defined`);
    }
    current = next.trim();
  }
  throw new Error(`token reference cycle resolving "${value}"`);
}

function generateThemeCSS() {
  const themes = source.themes;
  const order = themeIdsInEmissionOrder(themes);
  assertThemeParity(themes, order);

  let css = '/* ========================================\n';
  css += '   TIER 2: SEMANTIC ALIASES (theme-switchable)\n';
  css += '   ======================================== */\n\n';

  for (const id of order) {
    const theme = themes[id];
    const selector = theme.$default
      ? `[data-theme='${id}'],\n:root`
      : `[data-theme='${id}']`;

    css += `/* ${theme.$label} — ${theme.$scheme}${theme.$default ? ', default' : ''} */\n`;
    if (theme.$note) {
      // Wrap the note at ~92 cols so the generated file stays readable.
      const words = theme.$note.split(' ');
      let line = '/*';
      for (const word of words) {
        if ((line + ' ' + word).length > 92) {
          css += `${line}\n`;
          line = '  ';
        }
        line += (line === '  ' ? '' : ' ') + word;
      }
      css += `${line} */\n`;
    }
    css += `${selector} {\n`;
    for (const [name, value] of Object.entries(theme.tokens)) {
      css += `  --${name}: ${value};\n`;
    }
    css += '}\n\n';
  }

  return css;
}

// ========================================
// TS GENERATOR — uses backtick strings to handle quotes in font values
// ========================================
function generateTS() {
  let ts = '/* AUTO-GENERATED by tokens/build.cjs — do not edit directly.\n';
  ts += ' * Source: tokens/source.json\n';
  ts += ' */\n\n';

  ts += 'export const tokens = {\n';

  // Colors
  ts += '  color: {\n';
  for (const [family, ramp] of Object.entries(source.color)) {
    if (typeof ramp === 'string') {
      ts += `    ${family}: \`${ramp}\`,\n`;
      continue;
    }
    if (family === 'anchor') {
      ts += `    anchor: { semantic: \`${ramp.semantic}\`, code: \`${ramp.code}\` },\n`;
      continue;
    }
    ts += `    ${family}: { ${Object.entries(ramp).map(([k,v]) => `'${k}': \`${v}\``).join(', ')} },\n`;
  }
  ts += '  },\n\n';

  // Font, fontSize, radius, spacing, motion — all use backtick strings
  for (const [sectionName, sectionData] of Object.entries({ font: source.font, fontSize: source.fontSize, radius: source.radius, spacing: source.spacing, motion: source.motion })) {
    ts += `  ${sectionName}: {\n`;
    for (const [name, value] of Object.entries(sectionData)) {
      ts += `    ${name}: \`${value}\`,\n`;
    }
    ts += '  },\n\n';
  }

  ts += '} as const;\n\n';

  // Theme metadata — lets the theme picker enumerate what exists instead of
  // carrying a hand-maintained list that drifts from source.json.
  const order = themeIdsInEmissionOrder(source.themes);
  const primitives = primitiveMap(generateCSS());
  ts += '/** Every theme defined in tokens/source.json, in emission order (default first).\n';
  ts += ' *  `swatch` holds literal colours resolved at build time, so a preview renders\n';
  ts += ' *  in its own palette rather than in whichever theme is currently applied. */\n';
  ts += 'export const themes = [\n';
  for (const id of order) {
    const t = source.themes[id];
    const swatch = ['surface-base', 'color-accent', 'text-primary']
      .map((key) => `${key.replace(/-([a-z])/g, (_, c) => c.toUpperCase())}: '${resolveValue(t.tokens[key], t.tokens, primitives)}'`)
      .join(', ');
    ts += `  { id: '${id}', label: \`${t.$label}\`, scheme: '${t.$scheme}' as const, isDefault: ${Boolean(t.$default)}, swatch: { ${swatch} } },\n`;
  }
  ts += '] as const;\n\n';
  ts += 'export type ThemeId = (typeof themes)[number][\'id\'];\n\n';
  ts += `export const defaultThemeId: ThemeId = '${order[0]}';\n\n`;
  ts += '/** Narrowing guard for values read back out of localStorage. */\n';
  ts += 'export function isThemeId(value: unknown): value is ThemeId {\n';
  ts += '  return themes.some((t) => t.id === value);\n';
  ts += '}\n\n';

  ts += '/**\n';
  ts += ' * Semantic binding rules:\n';
  ts += ' * - Magenta (semantic) → intent, natural language, prompts, reasoning traces, agent dialogue\n';
  ts += ' * - Cyan (code) → artefacts, generated code, file trees, diffs, build logs\n';
  ts += ' * - Bridge → corpus callosum gradient at prompt→artefact transitions\n';
  ts += ' * - Neutral → chrome, structure, containers (majority of page)\n';
  ts += ' * Constraint: cap saturated-accent coverage at ~10% viewport area\n';
  ts += ' * Constraint: never place saturated magenta adjacent to saturated cyan\n';
  ts += ' * Constraint: pair hue with icon/label (never meaning by hue alone)\n';
  ts += ' */\n';

  return ts;
}

// Write outputs
const cssOutput = generateCSS() + generateThemeCSS();
const tsOutput = generateTS();

const cssPath = path.join(root, 'src', 'styles', 'generated-tokens.css');
const tsPath = path.join(root, 'src', 'lib', 'generated-tokens.ts');

fs.writeFileSync(cssPath, cssOutput);
fs.writeFileSync(tsPath, tsOutput);

console.log(`✓ CSS tokens written: ${cssPath} (${cssOutput.length} bytes)`);
console.log(`✓ TS tokens written: ${tsPath} (${tsOutput.length} bytes)`);
