/**
 * GeometricCloudGenerator — Deterministic semantic cloud topology via seeded PRNG.
 *
 * The core insight: Embed v4 produces 1536-dimensional vectors (points in space).
 * Instead of a flat vector index, we impose a GEOMETRIC STRUCTURE on the space
 * using cluster centers generated by a seeded Mulberry32 PRNG.
 *
 * Same seed → same cluster centers → same cloud topology.
 * Different seed → different cloud structure (different "cloud type").
 *
 * Cloud types (weather metaphor):
 *   Cumulonimbus — few large, dense clusters (deep domain expertise)
 *   Stratus      — many small, evenly-spread clusters (broad general knowledge)
 *   Cirrus       — sparse, wispy clusters (creative, divergent connections)
 *   Cumulus      — medium clusters with clear boundaries (balanced)
 *
 * The cloud topology controls:
 *   1. How many "brain regions" exist (cluster count)
 *   2. How spread out they are (cluster spread)
 *   3. How hierarchical they are (depth of sub-clusters)
 *   4. How dense each region is (points per cluster)
 *
 * Brain region mapping by agent role:
 *   Researcher → discovery/exploration regions (broad, many clusters)
 *   Auditor   → quality/coverage regions (dense, focused clusters)
 *   Verifier  → dependency/feasibility regions (dense, focused clusters)
 *   Designer  → architecture/structure regions (hierarchical, structured)
 *   Coder     → implementation/code regions (compact, practical)
 *
 * The "consciousness" emerges when you zoom into a specific region:
 *   Subconscious (reasoning disabled) = diffuse cloud, all regions accessible
 *   Conscious (reasoning active) = focused region, dense, ordered
 *
 * The seed can be:
 *   - Project-specific (derived from project ID)
 *   - Task-specific (derived from task type + complexity)
 *   - User-specific (derived from user ID)
 *   - Evolved by the Butterfly engine (optimized for VDR)
 */

/** Mulberry32 PRNG — pure math, no Node.js dependencies, Workers-compatible */
function mulberry32(seed: number): () => number {
  let s = seed >>> 0;
  return function (): number {
    s = (s + 0x6d2b79f5) | 0;
    let t = s;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Hash a string to a 32-bit unsigned integer for seeding */
function hashToSeed(str: string): number {
  let hash = 0x811c9dc5; // FNV-1a offset
  for (let i = 0; i < str.length; i++) {
    hash ^= str.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193);
  }
  return hash >>> 0;
}

/** Cloud topology type — controls how the PRNG generates cluster centers */
export type CloudType = 'cumulonimbus' | 'stratus' | 'cirrus' | 'cumulus';

/** Parameters that control the cloud's geometric structure */
export interface CloudTopologyParams {
  /** Number of cluster centers (brain regions) */
  clusterCount: number;
  /** Spread of clusters — how far apart they are in 1536d space */
  spread: number;
  /** Hierarchy depth — sub-clusters within clusters */
  hierarchyDepth: number;
  /** Density — how many points each cluster attracts */
  density: number;
  /** The cloud type derived from these params */
  type: CloudType;
}

/** A cluster center — a point in 1536d space that defines a "brain region" */
export interface ClusterCenter {
  id: number;
  /** 1536-dimensional vector */
  vector: number[];
  /** Human-readable label for this brain region */
  label: string;
  /** Which agent roles most often activate this region */
  primaryRoles: string[];
  /** Sub-cluster centers (if hierarchyDepth > 0) */
  subClusters?: ClusterCenter[];
}

/** A point in the semantic cloud — an embedding assigned to a cluster */
export interface CloudPoint {
  /** The original embedding vector */
  vector: number[];
  /** Which cluster this point belongs to */
  clusterId: number;
  /** Track record brightness: shipped=1.15, failed=0.7, unknown=1.0 */
  brightness: number;
  /** Metadata from the original lattice node */
  metadata: {
    agentRole: string;
    pipelineRunId: string;
    label: string;
    content?: string;
    nodeType: string;
  };
}

/**
 * Generate cloud topology parameters from a seed.
 * Different seeds produce qualitatively different cloud structures.
 *
 * @param seed - any string (project ID, task type, user ID, etc.)
 * @param complexity - task complexity (affects cluster count)
 */
export function generateCloudTopology(
  seed: string,
  complexity: 'simple' | 'moderate' | 'complex' = 'moderate'
): CloudTopologyParams {
  const rng = mulberry32(hashToSeed(seed));
  const r = rng();

  // Base cluster count on complexity
  const baseClusters = { simple: 5, moderate: 12, complex: 25 }[complexity];

  // PRNG determines cloud type
  let type: CloudType;
  if (r < 0.25) type = 'cumulonimbus';
  else if (r < 0.50) type = 'stratus';
  else if (r < 0.75) type = 'cirrus';
  else type = 'cumulus';

  // Cloud type adjusts the parameters
  const typeAdjustments: Record<CloudType, Partial<CloudTopologyParams>> = {
    cumulonimbus: { clusterCount: Math.max(3, Math.floor(baseClusters * 0.4)), spread: 0.3, hierarchyDepth: 2, density: 0.9 },
    stratus:      { clusterCount: Math.floor(baseClusters * 2), spread: 0.7, hierarchyDepth: 0, density: 0.3 },
    cirrus:       { clusterCount: Math.floor(baseClusters * 1.5), spread: 0.9, hierarchyDepth: 1, density: 0.15 },
    cumulus:      { clusterCount: baseClusters, spread: 0.5, hierarchyDepth: 1, density: 0.6 },
  };

  return { clusterCount: baseClusters, spread: 0.5, hierarchyDepth: 1, density: 0.5, type, ...typeAdjustments[type] };
}

/**
 * Generate deterministic cluster centers (brain regions) in 1536d space.
 * Same seed + same params = identical cluster centers.
 *
 * The cluster centers are generated using Gaussian distributions around
 * random points in the 1536d unit sphere. The spread parameter controls
 * how far apart the centers are.
 */
export function generateClusterCenters(
  seed: string,
  params: CloudTopologyParams,
  dimensions: number = 1536
): ClusterCenter[] {
  const rng = mulberry32(hashToSeed(seed));
  const centers: ClusterCenter[] = [];

  // Agent role labels for brain region mapping
  const roleMap = ['researcher', 'auditor', 'verifier', 'designer', 'coder'];

  for (let i = 0; i < params.clusterCount; i++) {
    const vector: number[] = new Array(dimensions);

    // Generate a random point in the unit sphere, scaled by spread
    let norm = 0;
    for (let d = 0; d < dimensions; d++) {
      // Box-Muller for Gaussian distribution
      const u1 = rng() + 1e-10;
      const u2 = rng();
      const z = Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
      vector[d] = z * params.spread;
      norm += vector[d] * vector[d];
    }

    // Normalize to unit length (cosine similarity space)
    norm = Math.sqrt(norm) || 1;
    for (let d = 0; d < dimensions; d++) {
      vector[d] /= norm;
    }

    const label = `region-${i}-${roleMap[i % roleMap.length]}`;

    centers.push({
      id: i,
      vector,
      label,
      primaryRoles: [roleMap[i % roleMap.length]],
    });

    // Generate sub-clusters if hierarchy depth > 0
    if (params.hierarchyDepth > 0) {
      const subCount = Math.max(2, Math.floor(params.clusterCount * 0.3));
      const subParams: CloudTopologyParams = {
        ...params,
        clusterCount: subCount,
        hierarchyDepth: params.hierarchyDepth - 1,
        spread: params.spread * 0.4, // Sub-clusters are tighter
      };
      centers[i].subClusters = generateClusterCenters(
        `${seed}-sub-${i}`,
        subParams,
        dimensions
      );
    }
  }

  return centers;
}

/**
 * Assign an embedding vector to its nearest cluster (brain region).
 * Uses cosine similarity — the standard metric for embedding space.
 */
export function assignCluster(
  embedding: number[],
  centers: ClusterCenter[]
): number {
  let bestCluster = 0;
  let bestSim = -Infinity;

  for (const center of centers) {
    const sim = cosineSimilarity(embedding, center.vector);
    if (sim > bestSim) {
      bestSim = sim;
      bestCluster = center.id;
    }
  }

  return bestCluster;
}

/**
 * Route a query to specific brain regions based on agent role.
 * Different agents activate different regions — like how different
 * brain areas light up for different tasks.
 *
 * Returns the cluster IDs that should be queried for this agent.
 */
export function routeToBrainRegions(
  agentRole: string,
  centers: ClusterCenter[],
  maxRegions: number = 3
): number[] {
  // Find regions whose primaryRoles match the agent
  const matching = centers
    .filter((c) => c.primaryRoles.includes(agentRole))
    .map((c) => c.id);

  // If not enough matching regions, add nearest ones
  if (matching.length < maxRegions) {
    for (const center of centers) {
      if (!matching.includes(center.id)) {
        matching.push(center.id);
        if (matching.length >= maxRegions) break;
      }
    }
  }

  return matching.slice(0, maxRegions);
}

/**
 * Cosine similarity between two vectors.
 * This is the core distance metric in embedding space.
 */
function cosineSimilarity(a: number[], b: number[]): number {
  let dot = 0;
  let normA = 0;
  let normB = 0;
  for (let i = 0; i < Math.min(a.length, b.length); i++) {
    dot += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  const denom = Math.sqrt(normA) * Math.sqrt(normB);
  return denom === 0 ? 0 : dot / denom;
}

/**
 * The "zoom" operation — condense a cloud region into a focused view.
 *
 * This is how consciousness emerges from the subconscious:
 * 1. The diffuse cloud has all points accessible (reasoning disabled)
 * 2. You "zoom" into a specific region (attention mechanism)
 * 3. The points in that region become denser, more ordered
 * 4. This condensed view is the conscious layer (reasoning active)
 *
 * @param points - all cloud points
 * @param clusterId - which brain region to zoom into
 * @param topN - how many points to include in the condensed view
 * @returns the condensed, ordered points for conscious processing
 */
export function zoomIntoRegion(
  points: CloudPoint[],
  clusterId: number,
  topN: number = 5
): CloudPoint[] {
  return points
    .filter((p) => p.clusterId === clusterId)
    .sort((a, b) => b.brightness - a.brightness) // Brightest (most successful) first
    .slice(0, topN);
}

/**
 * Generate a deterministic seed string from project + task context.
 * This seed controls the cloud topology — same context = same cloud.
 *
 * The seed is derived from:
 * - Project ID (or 'global' for cross-project memory)
 * - Task type (app type, complexity)
 * - Agent role (which brain regions to activate)
 *
 * This means:
 * - Same project + same task type = same cloud structure
 * - Different projects = different clouds (but comparable via seed)
 * - The Butterfly engine can evolve seeds for optimal VDR
 */
export function generateSeed(
  projectId: string | null,
  taskType: string,
  complexity: string,
  agentRole?: string
): string {
  const parts = [
    projectId ?? 'global',
    taskType,
    complexity,
    agentRole ?? 'any',
  ];
  return parts.join(':');
}

/**
 * Cloud fingerprint — a short hash that identifies a cloud's structure.
 * Same seed + same params = same fingerprint.
 * Used for comparing clouds across projects and finding "magic seeds".
 */
export function cloudFingerprint(
  seed: string,
  params: CloudTopologyParams
): string {
  const str = `${seed}:${params.type}:${params.clusterCount}:${params.spread}:${params.hierarchyDepth}`;
  let hash = 0x811c9dc5;
  for (let i = 0; i < str.length; i++) {
    hash ^= str.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193);
  }
  return (hash >>> 0).toString(16).padStart(8, '0');
}
