/**
 * Declares this Worker's main module so `ctx.exports` is typed.
 *
 * `ctx.exports` holds an automatically-configured loopback binding for every
 * top-level export of the entrypoint, which is how `Sandbox` reaches
 * `SandboxEgressProxy` without a service binding in wrangler.toml. Its type,
 * `Cloudflare.Exports`, is derived from `Cloudflare.GlobalProps["mainModule"]`
 * — normally generated by `wrangler types`, which this project does not run
 * (see src/env.ts's hand-written Env for the same reason).
 *
 * Without this the property exists at runtime and not in the type system, so
 * the call site would need a cast — and a cast there would mean a typo in the
 * export name became a runtime failure inside the security boundary rather
 * than a compile error. tests/integration/env.d.ts declares the same thing for
 * the integration suite, which compiles against its own tsconfig.
 */
declare global {
  namespace Cloudflare {
    interface GlobalProps {
      mainModule: typeof import('./index.js');
    }
  }
}

export {};
