"""
Auto-generated genome configuration — mirrors packages/shared/src/constants.ts.

DO NOT EDIT MANUALLY. This file is regenerated by the genome-sync workflow
from the TypeScript source of truth before each Monte Carlo run.

Source of truth: packages/shared/src/constants.ts (production)
API endpoint: /api/genome/status (public, no auth required)
"""

# === GENOME SOURCE OF TRUTH (mirrors TypeScript constants.ts) ===
GENOME_COUNT = 97  # Butterfly v8: 97 genes across 4 supergenes
POPULATION_MULTIPLIER = 11  # Storn & Price benchmark (10x + 10% safety)
MONTE_CARLO_POPULATION = GENOME_COUNT * POPULATION_MULTIPLIER  # 1067
DAILY_STAGING_BOTS = GENOME_COUNT  # 97 (1 per genome)
GENERATION_COUNT = 100  # Monte Carlo generations per cycle
MUTATION_RATE = 0.05  # 5% — prevents premature convergence (Goldberg/Schlatterbeck)
ELITISM_PERCENT = 10  # Top 10% preserved each generation
DIVERSITY_THRESHOLD = 20  # 20% diversity floor
SIM_SEED = 0xB1CC4F00D  # Butterfly seed — never change without full re-run

# === SIMULATION_PARAMS (mirrors TypeScript SIMULATION_PARAMS) ===
SIMULATION_PARAMS = {
    'genomeCount': GENOME_COUNT,
    'population': MONTE_CARLO_POPULATION,
    'dailyBots': DAILY_STAGING_BOTS,
    'generations': GENERATION_COUNT,
    'mutationRate': MUTATION_RATE,
    'elitism': ELITISM_PERCENT,
    'diversity': DIVERSITY_THRESHOLD,
    'seed': SIM_SEED,
    'parity': '1:1:1',
    'syncCheckIntervalSeconds': 300,
}

def get_population():
    """Returns the Monte Carlo population size (11x genome count)."""
    return MONTE_CARLO_POPULATION

def get_daily_bots():
    """Returns the daily staging bot count (1x genome count)."""
    return DAILY_STAGING_BOTS

def get_generations():
    """Returns the number of Monte Carlo generations per cycle."""
    return GENERATION_COUNT

def get_mutation_rate():
    """Returns the mutation rate (5%)."""
    return MUTATION_RATE

def get_genome_count():
    """Returns the current genome gene count."""
    return GENOME_COUNT
