/* AUTO-GENERATED by tokens/build.cjs — do not edit directly.
 * Source: tokens/source.json
 */

export const tokens = {
  color: {
    semantic: {
      '100': `#ffe6f5`,
      '200': `#ffc8e6`,
      '300': `#ff96c8`,
      '400': `#eb64aa`,
      '500': `#c8328c`,
      '600': `#a51e6e`,
      '700': `#7d1455`,
      '800': `#550f3c`,
      '900': `#320a23`,
    },
    code: {
      '100': `#dcfaff`,
      '200': `#b9f0ff`,
      '300': `#8cdcf5`,
      '400': `#5ac3e6`,
      '500': `#28a0d2`,
      '600': `#0078a5`,
      '700': `#005a82`,
      '800': `#003c64`,
      '900': `#002346`,
    },
    bridge: {
      '100': `#f0eafc`,
      '200': `#dccbf5`,
      '300': `#b8a5e8`,
      '400': `#9080d6`,
      '500': `#6a5cc0`,
      '600': `#4f42a0`,
      '700': `#3a2f7a`,
      '800': `#281f57`,
      '900': `#18133a`,
    },
    anchor: { semantic: `#FF00FF`, code: `#00FFFF` },
    neutral: {
      '0': `#ffffff`,
      '50': `#fafafa`,
      '100': `#f4f4f5`,
      '200': `#e4e4e7`,
      '300': `#d4d4d8`,
      '400': `#a1a1aa`,
      '500': `#71717a`,
      '600': `#52525b`,
      '700': `#3f3f46`,
      '750': `#27272a`,
      '800': `#18181b`,
      '900': `#09090b`,
      '950': `#050507`,
    },
    status: {
      success: `#0a8a5c`,
      warning: `#b36a00`,
      danger: `#c0362c`,
      info: `#1863dc`,
    },
  },

  font: {
    display: `'Space Grotesk', 'Inter', system-ui, sans-serif`,
    body: `'Inter', system-ui, -apple-system, sans-serif`,
    mono: `'Fira Code', 'SF Mono', 'Cascadia Code', monospace`,
  },

  fontSize: {
    display: `clamp(2.5rem, 5vw, 4.5rem)`,
    h1: `clamp(2rem, 4vw, 3rem)`,
    h2: `clamp(1.5rem, 3vw, 2rem)`,
    h3: `clamp(1.25rem, 2vw, 1.5rem)`,
    body: `clamp(0.875rem, 1vw, 1rem)`,
    caption: `clamp(0.75rem, 0.875vw, 0.875rem)`,
    code: `0.8125rem`,
  },

  radius: {
    sm: `6px`,
    md: `10px`,
    lg: `16px`,
    full: `9999px`,
  },

  spacing: {
    1: `4px`,
    2: `8px`,
    3: `12px`,
    4: `16px`,
    5: `20px`,
    6: `24px`,
    8: `32px`,
    14: `56px`,
  },

  motion: {
    easeStandard: `cubic-bezier(0.4, 0, 0.2, 1)`,
    easeEmphasized: `cubic-bezier(0.2, 0, 0, 1)`,
    durationFast: `150ms`,
    durationNormal: `240ms`,
    durationSlow: `400ms`,
  },
} as const;

/** Every theme defined in tokens/source.json, in emission order (default first).
 *  `swatch` holds literal colours resolved at build time, so a preview renders
 *  in its own palette rather than in whichever theme is currently applied. */
export const themes = [
  {
    id: 'dark',
    label: `Dark`,
    scheme: 'dark' as const,
    isDefault: true,
    swatch: {
      surfaceBase: '#050507',
      colorAccent: '#eb64aa',
      textPrimary: '#e5dce5',
    },
  },
  {
    id: 'light',
    label: `Light`,
    scheme: 'light' as const,
    isDefault: false,
    swatch: {
      surfaceBase: '#fafaf9',
      colorAccent: '#a51e6e',
      textPrimary: '#2c262b',
    },
  },
  {
    id: 'scorpio',
    label: `Scorpio`,
    scheme: 'dark' as const,
    isDefault: false,
    swatch: {
      surfaceBase: '#0a070a',
      colorAccent: '#e61934',
      textPrimary: '#e5dce5',
    },
  },
  {
    id: 'libra',
    label: `Libra`,
    scheme: 'light' as const,
    isDefault: false,
    swatch: {
      surfaceBase: '#fafaf9',
      colorAccent: '#4a6fa8',
      textPrimary: '#2c262b',
    },
  },
] as const;

export type ThemeId = (typeof themes)[number]['id'];

export const defaultThemeId: ThemeId = 'dark';

/** Narrowing guard for values read back out of localStorage. */
export function isThemeId(value: unknown): value is ThemeId {
  return themes.some((t) => t.id === value);
}

/**
 * Semantic binding rules:
 * - Magenta (semantic) → intent, natural language, prompts, reasoning traces, agent dialogue
 * - Cyan (code) → artefacts, generated code, file trees, diffs, build logs
 * - Bridge → corpus callosum gradient at prompt→artefact transitions
 * - Neutral → chrome, structure, containers (majority of page)
 * Constraint: cap saturated-accent coverage at ~10% viewport area
 * Constraint: never place saturated magenta adjacent to saturated cyan
 * Constraint: pair hue with icon/label (never meaning by hue alone)
 */
